### ISSUE TITLE
ElmCast/elm-vim may be unmaintained

### ISSUE THREAD

**Issue by andys8** [evancz/editor-plugins#1]
Hi there,

my understanding is that the vim plugin [`ElmCast/elm-vim`](https://github.com/ElmCast/elm-vim) is currently not maintained. I'm not sure to which degree its features are currently working or broken. Some of its core features rely on `elm-oracle` and `deoplete-elm` - both [broken since elm 0.19](https://github.com/pbogut/deoplete-elm/issues/3). (This may also be relevant for other plugins listed [here](https://github.com/ElmCast/elm-oracle#projects-that-use-elm-oracle) and completion in `elm-mode` for emacs is therefore [not working](https://github.com/jcollard/elm-mode/issues/142)).

## [Code Frequency](https://github.com/ElmCast/elm-vim/graphs/code-frequency)

![image](https://user-images.githubusercontent.com/13085980/66261393-b22aba00-e7cc-11e9-8cda-4e54cfbc787b.png)

## Issues

See [issues](https://github.com/ElmCast/elm-vim/issues) like

* https://github.com/ElmCast/elm-vim/issues/189
* https://github.com/ElmCast/elm-vim/issues/182
* https://github.com/ElmCast/elm-vim/issues/150 (maintainership transferred)

### Forks

There exist forks of ElmCast/elm-vim like https://github.com/Zaptic/elm-vim

### Elm Language Server

There is `elm-language-server` which can be used with many editors and [instructions for vim clients](https://github.com/elm-tooling/elm-language-server#vim). I would personally recommend this approach and collected a list of instructions how to setup tooling in [elm-tooling/elm-vim](https://github.com/elm-tooling/elm-vim).

### Ale

[`dense-analysis/ale`](https://github.com/dense-analysis/ale) contains an [elm make (only) linter](
https://github.com/dense-analysis/ale/blob/883978ece93bd19250d6d7e8b9659b48f23522e2/ale_linters/elm/make.vim)

**Comment by MrMatten** [comment]
Most functionality has become useless after the transition to elm (vs elm-make, elm-repel etc). What do work is indentation and colour scheme (maybe more)

**Comment by MrMatten** [comment]
Would be great if we could give some attention to one of the forks still being maintained. I will follow the one you linked to, if they have an interest in keeping at least base functionality up to date

**Comment by jcornaz** [comment]
https://github.com/Zaptic/elm-vim readme states:

> It appears that ElmCast/elm-vim is no longer being updated and does not support Elm 0.19. This fork has been updated for Elm 0.19 and includes some other changes. No major development is planned at the moment but we do plan to keep up with necessary changes and merge requests are welcome.

Considering that `ElmCast/elm-vim` still does not support elm `0.19` and looking at that readme and the state of the commit/issue/pr activity, I think it is quite clear that @Zaptic fork is a better alternative to @ElmCast original project.

Maybe it is time to update the readme so that it points to @Zaptic' fork?

**Comment by evancz** [comment]
I have not looked into #6 deeply, but they say that is the more updated version.
