### ISSUE TITLE
List is almost entirely out of date

### ISSUE THREAD

**Issue by tofusoul** [evancz/editor-plugins#10]
All the editor plugins cited in this list depends on elm-oracle for auto-completion. Elm-oracle is not maintained and does not support 0.19. Everyone looking at the official elm guide gets pointed here. The community should really discuss and fix. 

The elm language server seems to be the future, but there's no clear guidance for beginners. This list was supposed to point to such guides.

**Comment by evancz** [comment]
#5 and #6 pointed to newer versions of things. I am not deeply familiar with all the editors listed, so please do a PR if there are other links that should be removed or changed.
