### ISSUE TITLE
The Brackets extension doesn't support Elm 0.19

### ISSUE THREAD

**Issue by roebuk** [evancz/editor-plugins#9]
Someone on Slack just ran into trouble trying to using Elm and the brackets extension. It appears that the extension hasn't been updated for Elm 0.19 and upwards. As seen here:

https://github.com/tommot348/elm-brackets/blob/8efe67d4c27bb9381e1314a5ba9eb3b5d0ef6f06/modules/elm-package-json.js#L50

Perhaps it's worth removing Brackets as a recommended editor?

**Comment by evancz** [comment]
Makes sense. I'll do that for now.

I think someone should try to make an extension that does not do binary integration such that it is guaranteed to work independent of the Elm version. I hope they will message me so I know to update the link again.
